CREATE TABLE IF NOT EXISTS simulacao (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(5) NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parcelas (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulacao_id      INT REFERENCES simulacao(id) ON DELETE CASCADE,
    numero            INT,
    valor_amortizacao NUMERIC(18,2),
    valor_juros       NUMERIC(18,2),
    valor_prestacao   NUMERIC(18,2)
);